### ISSUE TITLE
Compiling Errors

### ISSUE THREAD

**Issue by crecord** [bakercp/ofxIO#23]
Hi Chris! 

Thanks for the great library. I am working on using ofxSerial with ofxIO to read some ints off an analog sensor an arduino. I am having some issues getting ofxIO to compile and will probably just bounce over to using straight up of Serial, but I thought I would take a minute to document the issues I was running into.

I am on osx 10.11.5 with OF 9.2. 

 
No Matching function for call to "ofToDataPath"
<img width="1397" alt="screen shot 2017-11-15 at 3 50 57 pm" src="https://user-images.githubusercontent.com/3160465/32859921-f38e9cd8-ca1d-11e7-9cbe-71fd72c7be87.png">

Can't find ofjson.h
<img width="1010" alt="screen shot 2017-11-15 at 3 54 28 pm" src="https://user-images.githubusercontent.com/3160465/32860001-2e8c1a36-ca1e-11e7-8c5c-36ed6e46bfa0.png">

unknown type name 'ofEventListener'
<img width="1388" alt="screen shot 2017-11-15 at 3 55 20 pm" src="https://user-images.githubusercontent.com/3160465/32860021-47beba2c-ca1e-11e7-839d-4a169e76e862.png">

**Comment by bakercp** [comment]
Hey @crecord the master branch works with the master branch of openFrameworks.  The stable branch works with 0.9.8 (see the README.md for more).
